export * as namespaceURI from "./namespaceURI";
export * from "./presentation";
export * from "./slideIdList";
export * from "./slideId";
export * from "./slide";
export * from "./commonSlideData";
export * from "./nonVisualGroupShapeProperties";
export * from "./nonVisualShapeProperties";
export * from "./nonVisualPictureProperties";
export * from "./cNvPr";
export * from "./shapeTree";
export * from "./groupShape";
export * from "./shape";
export * from "./picture";